name: Deploy functions to Firebase (Production)

on:
  push:
    branches:
      - main
    paths:
      - 'firebase/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: install-firebase-tools
        run: npm install -g firebase-tools
      - name: install-dependencies
        run: cd firebase/functions && npm i
      - name: deploy-functions-to-firebase-production
        run: firebase use chatbridge-live && npm run deploy