name: Deploy backend to Heroku (Staging)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: set-heroku-dev-remote
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: git remote add heroku https://:{{ secrets.HEROKU_API_KEY }}@git.heroku.com/service-chatbridge-dev.git
      - name: deploy-backend-to-heroku-dev
        run: git subtree push --prefix backend heroku master