name: Deploy backend to Heroku (Production)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "service-chatbridge-prod"
          heroku_email: "mfaizk2008@gmail.com"
          remote_branch: master
          appdir: "backend"
