name: Deploy backend to Heroku (Production)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: set-heroku-prod-remote
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: git remote add heroku https://:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/service-chatbridge-prod.git
      - name: deploy-backend-to-heroku-prod
        run: git subtree push --prefix backend heroku master