name: Deploy backend to Heroku (Staging)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: deploy-backend-to-heroku-dev
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku git:remote --app service-chatbridge-dev && git subtree push --prefix backend heroku master
