name: Deploy backend to Heroku (Production)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: set-heroku-dev-remote
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku git:remote --app service-chatbridge-prod
      - name: deploy-backend-to-heroku-prod
        run: git subtree push --prefix backend heroku master