name: Deploy functions to Firebase (Staging)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'firebase/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: install-dependencies
        run: cd firebase/functions && npm i
      - name: install-firebase-tools
        run: npm i firebase-tools
      - name: deploy-functions-to-firebase-staging
        run: firebase use uniofcam-chat && npm run deploy