name: Deploy backend to Heroku (Staging)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: set-heroku-dev-remote
        run: heroku git:remote --app service-chatbridge-dev
      - name: deploy-backend-to-heroku-dev
        run: git subtree push --prefix backend heroku master