name: Update branch config (development only)

on:
  pull_request:
    types:
      - opened
    branches-ignore:
      - main

jobs:
  update_branch_config:
    runs-on: ubuntu-latest
    secrets:
      branch_config_token: ${{ secrets.BRANCH_CONFIG_TOKEN }}
    steps:
      - name: Update branch config
        run: curl -v -X POST 'https://service-chatbridge-staging.herokuapp.com/config/branch/${{ branch_config_token }}' -H 'Content-Type: application/json' --data-raw '{"name":${{ github.head_ref }},"num":${{ github.event.number }}}'