name: Update branch config (development only)

on:
  pull_request:
    types:
      - opened
    branches-ignore:
      - main

jobs:
  update_branch_config:
    runs-on: ubuntu-latest
    env:
      NAME: ${{ github.head_ref }}
      NUM: ${{ github.event.number }}
      TOKEN: ${{ secrets.BRANCH_CONFIG_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'staging'
      - run: ./scripts/ci/branch_config